import unicodedata
from datetime import date
import streamlit as st
from fpdf import FPDF
from research_agent import run_agent


def _build_pdf(pmid: str, summary: str) -> bytes:
    def clean(text: str) -> str:
        return unicodedata.normalize("NFKD", text).encode("latin-1", "ignore").decode("latin-1")

    NAVY = (15, 23, 42)
    TEAL = (45, 212, 191)
    DARK_GREY = (51, 65, 85)
    WHITE = (241, 245, 249)

    pdf = FPDF()
    pdf.set_margins(20, 20, 20)
    pdf.add_page()

    # Header bar
    pdf.set_fill_color(*NAVY)
    pdf.rect(0, 0, 210, 22, style="F")

    pdf.set_y(6)
    pdf.set_x(10)
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*WHITE)
    pdf.cell(0, 10, "Research Assistant", align="L")

    pdf.set_y(6)
    pdf.set_x(10)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*TEAL)
    pdf.cell(0, 10, clean(f"PMID: {pmid}"), align="R")

    # Teal rule below header
    pdf.set_y(23)
    pdf.set_draw_color(*TEAL)
    pdf.set_line_width(0.8)
    pdf.line(10, 24, 200, 24)

    # Section title
    pdf.set_y(30)
    pdf.set_x(10)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*TEAL)
    pdf.cell(0, 10, "Summary", ln=True)

    # Body text
    pdf.set_x(10)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*DARK_GREY)
    pdf.multi_cell(0, 7, clean(summary))

    # Footer
    footer_y = 277
    pdf.set_draw_color(*TEAL)
    pdf.set_line_width(0.5)
    pdf.line(10, footer_y, 200, footer_y)

    pdf.set_y(footer_y + 2)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*DARK_GREY)
    pdf.set_x(10)
    pdf.cell(0, 5, "Generated by Research Assistant", align="L")
    pdf.set_y(footer_y + 2)
    pdf.set_x(10)
    pdf.cell(0, 5, date.today().strftime("%Y-%m-%d"), align="R")

    return bytes(pdf.output())


# ── UI ──────────────────────────────────────────────────────────────────────

st.markdown("""
<style>
.header-card {
    background: #1E293B;
    border-left: 4px solid #2DD4BF;
    padding: 1.2rem 1.5rem;
    border-radius: 8px;
    margin-bottom: 1.5rem;
}
.header-card h1 {
    color: #F1F5F9;
    margin: 0 0 0.25rem 0;
    font-size: 1.8rem;
}
.header-card p {
    color: #94A3B8;
    margin: 0;
    font-size: 0.95rem;
}
.teal-divider {
    border: none;
    border-top: 1px solid #2DD4BF;
    margin: 1.5rem 0;
    opacity: 0.5;
}
.summary-card {
    background: #1E293B;
    border: 1px solid #334155;
    border-radius: 8px;
    padding: 1.5rem;
    color: #F1F5F9;
    line-height: 1.7;
}
</style>

<div class="header-card">
    <h1>Research Assistant</h1>
    <p>AI-powered paper summarisation</p>
</div>
""", unsafe_allow_html=True)

pmid = st.text_input("PubMed ID")

if st.button("Fetch & Summarise"):
    if not pmid.strip():
        st.warning("Please enter a PubMed ID.")
    else:
        with st.spinner("Fetching and summarising..."):
            st.session_state["summary"] = run_agent(pmid.strip())
            st.session_state["pmid"] = pmid.strip()

if "summary" in st.session_state:
    summary = st.session_state["summary"]
    saved_pmid = st.session_state["pmid"]

    st.markdown('<hr class="teal-divider">', unsafe_allow_html=True)

    st.markdown(
        f'<div class="summary-card">{summary}</div>',
        unsafe_allow_html=True,
    )

    st.markdown('<hr class="teal-divider">', unsafe_allow_html=True)

    col1, col2 = st.columns(2)

    with col1:
        st.download_button(
            label="Download as Markdown",
            data=summary,
            file_name=f"{saved_pmid}.md",
            mime="text/markdown",
            use_container_width=True,
        )

    with col2:
        st.download_button(
            label="Download as PDF",
            data=_build_pdf(saved_pmid, summary),
            file_name=f"{saved_pmid}.pdf",
            mime="application/pdf",
            use_container_width=True,
        )
