import re
import unicodedata
from datetime import date
import streamlit as st
from fpdf import FPDF
from research_agent import run_agent


def _build_pdf(pmid: str, summary: str) -> bytes:
    def clean(text: str) -> str:
        return unicodedata.normalize("NFKD", text).encode("latin-1", "ignore").decode("latin-1")

    def strip_md(text: str) -> str:
        text = re.sub(r"\*+", "", text)
        text = re.sub(r"^#+\s*", "", text, flags=re.MULTILINE)
        return text.strip()

    NAVY        = (15, 23, 42)
    TEAL        = (45, 212, 191)
    LIGHT_GREY  = (248, 250, 252)
    BODY        = (51, 65, 85)
    MUTED       = (148, 163, 184)
    BORDER      = (226, 232, 240)
    WHITE       = (255, 255, 255)

    # ── Parse sections ────────────────────────────────────────────────────
    title = ""
    authors = ""
    journal = ""
    key_points: list[str] = []
    body_lines: list[str] = []

    for line in summary.splitlines():
        s = line.strip()
        if s.startswith("**Title:**"):
            title = strip_md(s[len("**Title:**"):].strip())
        elif s.startswith("**Authors:**"):
            authors = strip_md(s[len("**Authors:**"):].strip())
        elif s.startswith("**Journal:**"):
            journal = strip_md(s[len("**Journal:**"):].strip())
        elif s.startswith("-"):
            kp = strip_md(s[1:].strip())
            if kp:
                key_points.append(kp)
        elif s:
            body_lines.append(strip_md(s))

    body_text = "\n".join(body_lines)
    authors_journal = "\n".join(x for x in [authors, journal] if x)

    pdf = FPDF()
    pdf.set_margins(20, 20, 20)
    pdf.add_page()

    # ── 1. HEADER (full-width navy, height 40) ────────────────────────────
    pdf.set_fill_color(*NAVY)
    pdf.rect(0, 0, 210, 40, style="F")

    pdf.set_xy(20, 11)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*TEAL)
    pdf.cell(100, 6, "RESEARCH ASSISTANT")

    pdf.set_xy(20, 19)
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*WHITE)
    pdf.cell(100, 12, "Paper Summary")

    pdf.set_xy(120, 11)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*MUTED)
    pdf.cell(70, 6, "PMID", align="R")

    pdf.set_xy(120, 19)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*TEAL)
    pdf.cell(70, 12, clean(pmid), align="R")

    # ── 2. TEAL RULE (full-width, height 3) ───────────────────────────────
    pdf.set_fill_color(*TEAL)
    pdf.rect(0, 40, 210, 3, style="F")

    # ── 3. BODY ───────────────────────────────────────────────────────────
    y = 53

    def section_label(label: str) -> None:
        nonlocal y
        pdf.set_xy(20, y)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*TEAL)
        pdf.cell(170, 6, label.upper())
        y += 6

    def body_block(text: str, size: int = 11, lh: int = 6) -> None:
        nonlocal y
        pdf.set_xy(20, y)
        pdf.set_font("Helvetica", "", size)
        pdf.set_text_color(*BODY)
        pdf.multi_cell(170, lh, clean(text))
        y = pdf.get_y()

    if title:
        section_label("TITLE")
        body_block(title)
        y += 8

    if authors_journal:
        section_label("AUTHORS & JOURNAL")
        body_block(authors_journal)
        y += 8

    # Thin grey rule before Summary
    pdf.set_draw_color(*BORDER)
    pdf.set_line_width(0.3)
    pdf.line(20, y, 190, y)
    y += 6

    if body_text:
        section_label("SUMMARY")
        body_block(body_text)
        y += 8

    # ── 4. KEY POINTS BLOCK ───────────────────────────────────────────────
    if key_points:
        section_label("KEY POINTS")
        y += 2

        bx, bw = 20, 170
        block_start = y

        # Top padding row (grey background)
        pdf.set_fill_color(*LIGHT_GREY)
        pdf.set_xy(bx, y)
        pdf.cell(bw, 4, "", fill=True)
        y += 4

        for kp in key_points:
            pdf.set_xy(bx, y)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(*BODY)
            pdf.set_fill_color(*LIGHT_GREY)
            pdf.multi_cell(bw, 6, clean(f"     - {kp}"), fill=True)
            y = pdf.get_y()

        # Bottom padding row
        pdf.set_fill_color(*LIGHT_GREY)
        pdf.set_xy(bx, y)
        pdf.cell(bw, 4, "", fill=True)
        y += 4

        # 3pt teal left border drawn over grey background
        pdf.set_fill_color(*TEAL)
        pdf.rect(bx, block_start, 3, y - block_start, style="F")

    # ── 5. FOOTER ─────────────────────────────────────────────────────────
    footer_y = 282
    pdf.set_draw_color(*BORDER)
    pdf.set_line_width(0.3)
    pdf.line(0, footer_y, 210, footer_y)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*MUTED)

    pdf.set_xy(20, footer_y + 3)
    pdf.cell(85, 5, "Generated by Research Assistant", align="L")

    pdf.set_xy(105, footer_y + 3)
    pdf.cell(85, 5, date.today().strftime("%Y-%m-%d"), align="R")

    return bytes(pdf.output())


# ── UI ──────────────────────────────────────────────────────────────────────

st.markdown("""
<style>
.header-card {
    background: #1E293B;
    border-left: 4px solid #2DD4BF;
    padding: 1.2rem 1.5rem;
    border-radius: 8px;
    margin-bottom: 1.5rem;
}
.header-card h1 {
    color: #F1F5F9;
    margin: 0 0 0.25rem 0;
    font-size: 1.8rem;
}
.header-card p {
    color: #94A3B8;
    margin: 0;
    font-size: 0.95rem;
}
.teal-divider {
    border: none;
    border-top: 1px solid #2DD4BF;
    margin: 1.5rem 0;
    opacity: 0.5;
}
.summary-card {
    background: #1E293B;
    border: 1px solid #334155;
    border-radius: 8px;
    padding: 1.5rem;
    color: #F1F5F9;
    line-height: 1.7;
}
</style>

<div class="header-card">
    <h1>Research Assistant</h1>
    <p>AI-powered paper summarisation</p>
</div>
""", unsafe_allow_html=True)

pmid = st.text_input("PubMed ID")

if st.button("Fetch & Summarise"):
    if not pmid.strip():
        st.warning("Please enter a PubMed ID.")
    else:
        with st.spinner("Fetching and summarising..."):
            st.session_state["summary"] = run_agent(pmid.strip())
            st.session_state["pmid"] = pmid.strip()

if "summary" in st.session_state:
    summary = st.session_state["summary"]
    saved_pmid = st.session_state["pmid"]

    st.markdown('<hr class="teal-divider">', unsafe_allow_html=True)

    st.markdown(
        f'<div class="summary-card">{summary}</div>',
        unsafe_allow_html=True,
    )

    st.markdown('<hr class="teal-divider">', unsafe_allow_html=True)

    col1, col2 = st.columns(2)

    with col1:
        st.download_button(
            label="Download as Markdown",
            data=summary,
            file_name=f"{saved_pmid}.md",
            mime="text/markdown",
            use_container_width=True,
        )

    with col2:
        st.download_button(
            label="Download as PDF",
            data=_build_pdf(saved_pmid, summary),
            file_name=f"{saved_pmid}.pdf",
            mime="application/pdf",
            use_container_width=True,
        )
