import re
import unicodedata
from datetime import date
import os
import streamlit as st
import anthropic
from fpdf import FPDF
from research_agent import run_agent

_client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

_SYSTEM_PROMPT = (
    "You are a research assistant helping a computational biologist "
    "understand scientific papers. Answer questions clearly and "
    "concisely based on the paper summary in the conversation. "
    "If asked something not covered in the summary, say so clearly."
)


def _build_pdf(pmid: str, summary: str) -> bytes:
    def clean(text: str) -> str:
        return unicodedata.normalize("NFKD", text).encode("latin-1", "ignore").decode("latin-1")

    def strip_md(text: str) -> str:
        text = re.sub(r"\*+", "", text)
        text = re.sub(r"^#+\s*", "", text, flags=re.MULTILINE)
        text = re.sub(r"^[-*]\s+", "", text, flags=re.MULTILINE)
        return text.strip()

    NAVY       = (15, 23, 42)
    TEAL       = (45, 212, 191)
    LIGHT_GREY = (248, 250, 252)
    BODY       = (51, 65, 85)
    MUTED      = (148, 163, 184)
    BORDER     = (226, 232, 240)
    WHITE      = (255, 255, 255)

    # ── Parse sections ────────────────────────────────────────────────────
    title = ""
    authors = ""
    journal = ""
    key_points: list[str] = []
    body_lines: list[str] = []

    m = re.search(r'\*\*Title:\*\*\s*(.*?)(?=\*\*)', summary, re.DOTALL)
    if m:
        title = strip_md(m.group(1).strip())

    for line in summary.splitlines():
        s = line.strip()
        if not s:
            continue
        if re.match(r'\*\*Title:', s):
            continue
        elif re.match(r'\*\*Authors:\*\*', s):
            authors = strip_md(s.split('**Authors:**', 1)[1].strip())
        elif re.match(r'\*\*Journal:\*\*', s):
            journal = strip_md(s.split('**Journal:**', 1)[1].strip())
        elif re.match(r'^[-*]\s+', s):
            kp = strip_md(re.sub(r'^[-*]\s+', '', s))
            if kp:
                key_points.append(kp)
        elif not re.match(r'^(#+|\*\*)', s):
            body_lines.append(strip_md(s))

    body_text = "\n".join(body_lines)
    authors_journal = "\n".join(x for x in [authors, journal] if x)

    class ReportPDF(FPDF):
        def footer(self):
            self.set_draw_color(*BORDER)
            self.set_line_width(0.3)
            self.line(0, self.h - 15, self.w, self.h - 15)
            self.set_font("Helvetica", "", 9)
            self.set_text_color(*MUTED)
            self.set_xy(20, self.h - 12)
            self.cell(85, 5, "Generated by Research Assistant", align="L")
            self.set_xy(105, self.h - 12)
            self.cell(85, 5, date.today().strftime("%Y-%m-%d"), align="R")

    pdf = ReportPDF()
    pdf.set_margins(20, 15, 20)
    pdf.set_auto_page_break(True, margin=15)
    pdf.add_page()

    w = pdf.w
    effective_width = w - 40

    # ── 1. HEADER ─────────────────────────────────────────────────────────
    pdf.set_fill_color(*NAVY)
    pdf.rect(0, 0, w, 40, style="F")

    pdf.set_xy(20, 11)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*TEAL)
    pdf.cell(0, 6, "RESEARCH ASSISTANT")

    pdf.set_xy(20, 19)
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*WHITE)
    pdf.cell(0, 8, "Paper Summary")

    pdf.set_xy(20, 11)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*MUTED)
    pdf.cell(effective_width, 6, "PMID", align="R")

    pdf.set_xy(20, 19)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*TEAL)
    pdf.cell(effective_width, 8, clean(pmid), align="R")

    # ── 2. TEAL RULE ──────────────────────────────────────────────────────
    pdf.set_fill_color(*TEAL)
    pdf.rect(0, 40, w, 3, style="F")

    # ── 3. BODY ───────────────────────────────────────────────────────────
    y = 53

    def section_label(label: str) -> None:
        nonlocal y
        pdf.set_xy(20, y)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*TEAL)
        pdf.cell(effective_width, 5, label.upper())
        y += 6

    def body_block(text: str) -> None:
        nonlocal y
        pdf.set_xy(20, y)
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(*BODY)
        pdf.multi_cell(effective_width, 5, clean(text))
        y = pdf.get_y()

    def grey_rule() -> None:
        nonlocal y
        pdf.set_draw_color(*BORDER)
        pdf.set_line_width(0.3)
        pdf.line(20, y, w - 20, y)
        y += 6

    sections = []
    if title:
        sections.append(("TITLE", title))
    if authors_journal:
        sections.append(("AUTHORS & JOURNAL", authors_journal))
    if body_text:
        sections.append(("SUMMARY", body_text))

    for i, (label, text) in enumerate(sections):
        section_label(label)
        body_block(text)
        if i < len(sections) - 1 or key_points:
            y += 4
            grey_rule()

    # ── 4. KEY POINTS BLOCK ───────────────────────────────────────────────
    if key_points:
        section_label("KEY POINTS")
        y += 2

        bx, bw = 20, effective_width
        block_start = y

        pdf.set_fill_color(*LIGHT_GREY)
        pdf.set_xy(bx, y)
        pdf.cell(bw, 4, "", fill=True)
        y += 4

        for kp in key_points:
            pdf.set_xy(bx, y)
            pdf.set_font("Helvetica", "", 11)
            pdf.set_text_color(*BODY)
            pdf.set_fill_color(*LIGHT_GREY)
            pdf.multi_cell(bw, 5, clean(f"    - {kp}"), fill=True)
            y = pdf.get_y()

        pdf.set_fill_color(*LIGHT_GREY)
        pdf.set_xy(bx, y)
        pdf.cell(bw, 4, "", fill=True)
        y += 4

        pdf.set_fill_color(*TEAL)
        pdf.rect(bx, block_start, 3, y - block_start, style="F")

    return bytes(pdf.output())


# ── UI ──────────────────────────────────────────────────────────────────────

st.markdown("""
<style>
.header-card {
    background: #1E293B;
    border-left: 4px solid #2DD4BF;
    padding: 1.2rem 1.5rem;
    border-radius: 8px;
    margin-bottom: 1.5rem;
}
.header-card h1 {
    color: #F1F5F9;
    margin: 0 0 0.25rem 0;
    font-size: 1.8rem;
}
.header-card p {
    color: #94A3B8;
    margin: 0;
    font-size: 0.95rem;
}
.teal-divider {
    border: none;
    border-top: 1px solid #2DD4BF;
    margin: 1.5rem 0;
    opacity: 0.5;
}
.summary-card {
    background: #1E293B;
    border: 1px solid #334155;
    border-radius: 8px;
    padding: 1.5rem;
    color: #F1F5F9;
    line-height: 1.7;
}
</style>

<div class="header-card">
    <h1>Research Assistant</h1>
    <p>AI-powered paper summarisation</p>
</div>
""", unsafe_allow_html=True)

if "messages" not in st.session_state:
    st.session_state.messages = []

pmid = st.text_input("PubMed ID")

if st.button("Fetch & Summarise"):
    if not pmid.strip():
        st.warning("Please enter a PubMed ID.")
    else:
        with st.spinner("Fetching and summarising..."):
            summary, fetched_text = run_agent(pmid.strip())
            st.session_state["summary"] = summary
            st.session_state["pmid"] = pmid.strip()
            st.session_state["fetched_text"] = fetched_text
            st.session_state.messages = [
                {"role": "user", "content": f"Fetch and summarise PMID {pmid.strip()}"},
                {"role": "assistant", "content": summary},
            ]

if "summary" in st.session_state:
    summary = st.session_state["summary"]
    saved_pmid = st.session_state["pmid"]

    st.markdown('<hr class="teal-divider">', unsafe_allow_html=True)

    st.markdown(
        f'<div class="summary-card">{summary}</div>',
        unsafe_allow_html=True,
    )

    fetched_text = st.session_state.get("fetched_text", "")
    if "[Source: Full text" in fetched_text:
        st.caption("📄 Full text retrieved via PubMed Central")
    elif "[Source: Abstract only" in fetched_text:
        st.caption("📋 Abstract only — full text not available in PMC")

    st.markdown('<hr class="teal-divider">', unsafe_allow_html=True)

    col1, col2 = st.columns(2)

    with col1:
        st.download_button(
            label="Download as Markdown",
            data=summary,
            file_name=f"{saved_pmid}.md",
            mime="text/markdown",
            use_container_width=True,
        )

    with col2:
        st.download_button(
            label="Download as PDF",
            data=_build_pdf(saved_pmid, summary),
            file_name=f"{saved_pmid}.pdf",
            mime="application/pdf",
            use_container_width=True,
        )

    st.markdown('<hr class="teal-divider">', unsafe_allow_html=True)

    for msg in st.session_state.messages[2:]:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    if question := st.chat_input("Ask a follow-up question about this paper..."):
        st.session_state.messages.append({"role": "user", "content": question})
        with st.chat_message("user"):
            st.markdown(question)

        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                api_response = _client.messages.create(
                    model="claude-sonnet-4-6",
                    max_tokens=1024,
                    system=_SYSTEM_PROMPT,
                    messages=st.session_state.messages,
                )
                answer = api_response.content[0].text
            st.markdown(answer)

        st.session_state.messages.append({"role": "assistant", "content": answer})
